"use client"

import { useEffect, useState } from "react"
import { FlaskConical } from "lucide-react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { DEMO_WELCOME_COOKIE } from "@/lib/auth/demo-session"

function hasWelcomeCookie(): boolean {
  return document.cookie
    .split("; ")
    .some((c) => c.startsWith(`${DEMO_WELCOME_COOKIE}=`))
}

function clearWelcomeCookie() {
  // Expire it immediately so a reload doesn't re-open the modal.
  document.cookie = `${DEMO_WELCOME_COOKIE}=; path=/; max-age=0; samesite=lax`
}

/**
 * Shown once when a visitor enters via "Try the live demo". The demo route sets
 * the welcome cookie; we read it on mount, open the modal, and clear the cookie
 * so it fires exactly on entry and never again for the session.
 */
export function DemoDisclaimer() {
  const [open, setOpen] = useState(false)

  useEffect(() => {
    if (hasWelcomeCookie()) {
      clearWelcomeCookie()
      setOpen(true)
    }
  }, [])

  function handleOpenChange(next: boolean) {
    setOpen(next)
    if (!next) clearWelcomeCookie()
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent showCloseButton={false}>
        <DialogHeader>
          <span className="flex size-10 items-center justify-center rounded-full bg-primary/10 text-primary">
            <FlaskConical className="size-5" />
          </span>
          <DialogTitle>This is sample data</DialogTitle>
          <DialogDescription>
            Everything you see here — balances, transactions, accounts — is
            artificial data generated by the{" "}
            <a
              href="https://plaid.com/docs/sandbox/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Plaid Sandbox API
            </a>
            . No real bank accounts or financial information are involved.
          </DialogDescription>
        </DialogHeader>
        <DialogFooter>
          <Button onClick={() => handleOpenChange(false)} className="h-9">
            Got it
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
